containers/ecr-viewer/src/app/components/EcrTableClient.tsx, containers/ecr-viewer/src/app/components/SortButton.tsx, containers/ecr-viewer/src/app/tests/components/__snapshots__/EcrTable.test.tsx.snap
Renames the ID of the sort button for the Encounter Date column to `encounter_date`. In addition use the column value in the aria-label.
Fixes #290
=> fix: rename report_date to encounter_date in EcrTableClient

containers/ecr-viewer/src/app/components/EcrPaginationWrapper.tsx, containers/ecr-viewer/src/app/tests/components/__snapshots__/ActiveProblems.test.tsx.snap, containers/ecr-viewer/src/app/tests/components/__snapshots__/Clinical.test.tsx.snap, containers/ecr-viewer/src/app/tests/components/__snapshots__/EcrPaginationWrapper.test.tsx.snap, containers/ecr-viewer/src/app/tests/components/__snapshots__/Immunizations.test.tsx.snap, containers/ecr-viewer/src/app/tests/components/__snapshots__/LabInfo.test.tsx.snap, containers/ecr-viewer/src/app/tests/services/__snapshots__/socialHistoryService.test.tsx.snap, containers/ecr-viewer/src/app/view-data/components/EvaluateTable.tsx, containers/ecr-viewer/src/styles/common.scss, containers/ecr-viewer/src/styles/custom-styles.scss, containers/ecr-viewer/src/styles/custom-uswds-styles.scss, containers/ecr-viewer/src/styles/ecr-library.scss, containers/ecr-viewer/src/styles/ecr-viewer.scss, containers/ecr-viewer/src/styles/styles.scss, containers/ecr-viewer/src/styles/utilities.scss
Split up our `custom-styles.scss` into
- `custom-uswds-styles`
- `common`
- `ecr-viewer`
- `ecr-library`
- and move some of the declartions into already existing `utilities`
Fixes #169
=> refactor: break up `.scss` files into more clear scopes

.github/dependabot.yml
- Dependabot should only run on sundays so it doesn't fill up the action queue while we are actively working
- Set a limit of 2 updates per week so we don't get spammed
=> ci: limit dependabot

containers/ecr-viewer/src/app/components/Filters.tsx
Remove the key "all" on a div in filter condition code. It's unnecessary.
Fixes #24
=> fix: remove unnecessary key on filter condition div

containers/ecr-viewer/src/app/components/EcrTableHeader.tsx, containers/ecr-viewer/src/app/tests/components/__snapshots__/EcrTableHeader.test.tsx.snap
In #337 a couple classnames got lost. This adds them back.
=> fix: restore ecr library table stickiness

containers/ecr-viewer/design-review/design-review.sh, containers/ecr-viewer/e2e/integrated/auth.spec.ts
- Updates design review script to use the new repo
- Increases timeout for integrated auth e2e test to 30 seconds.
#411 
Anything else the review team should know?
[//]: # "PR title: Remember to name your PR descriptively!"
=> chore: Update design review script to use new repo

containers/ecr-viewer/src/styles/ecr-viewer.scss
When the screen is too short to house all of the side nav, let it scroll.
Fixes #490
Side nav should always be navigable
https://github.com/user-attachments/assets/9e84c0d9-32ad-4c55-90cf-b883d7a21f02
=> fix: side nav scroll

containers/ecr-viewer/seed-scripts/baseECR/star-wars/yoda-zika-v1-positive/CDA_eICR.xml, containers/ecr-viewer/src/app/tests/components/Clinical.test.tsx, containers/ecr-viewer/src/app/utils/evaluate/fhir-paths.ts, containers/ecr-viewer/src/app/utils/evaluate/index.ts, containers/ecr-viewer/src/app/view-data/components/EcrDocument/clinical-data.tsx
Get and display all vital signs from the bundle and display in a consistent order instead of only getting height, weight, and BMI.
Fixes #499
All vital signs should be displayed
Before:
After:
=> fix: generify vital sign evaluation and display

containers/ecr-viewer/e2e/dual/ecr-library.spec.ts, containers/ecr-viewer/src/app/components/EcrTableLoading.tsx, containers/ecr-viewer/src/app/tests/components/__snapshots__/EcrTableLoading.test.tsx.snap
Add e2e tests to ensure library sorting is working.
Fixes #580
Sorting tests for each column in the eCR Library
This PR tests that the order of the columns did reverse when switched from ascending to descending? Is this enough? or should it more strictly check a sort order?
=> test: add e2e library sorting tests

containers/ecr-viewer/src/app/services/formatService.ts, containers/ecr-viewer/src/app/tests/services/formatService.test.tsx, containers/ecr-viewer/src/app/utils/evaluate/fhir-paths.ts, containers/ecr-viewer/src/app/utils/evaluate/index.ts, test-data/fhir/BundleLab.json
Format observation reference ranges consistent with other quantities (when low/high available)
Fixes #103
=> fix: consistently format units in reference ranges

containers/ecr-viewer/integration/save-fhir-data-service.test.ts, containers/ecr-viewer/jest.config.js, containers/ecr-viewer/src/app/api/fhir-data/fhir-data-service.ts, containers/ecr-viewer/src/app/api/save-fhir-data/save-fhir-data-service.ts, containers/ecr-viewer/src/app/data/blobStorage/azureClient.ts, containers/ecr-viewer/src/app/data/blobStorage/gcpClient.ts, containers/ecr-viewer/src/app/data/blobStorage/s3Client.ts, containers/ecr-viewer/src/app/data/blobStorage/utils.ts, containers/ecr-viewer/src/app/tests/api/save-fhir-data/save-fhir-data-service.test.ts, containers/ecr-viewer/src/app/tests/data/blobStorage/azureClient.test.ts, containers/ecr-viewer/src/app/tests/data/blobStorage/gcpClient.test.ts, containers/ecr-viewer/src/app/tests/data/blobStorage/s3Client.test.ts, containers/ecr-viewer/tsconfig.json
Handle rolling back fhir- or meta- data if the other fails when trying to save both.
Highlights:
* Kysely transactions roll back when an error is thrown, so check if fhir saving failed inside the transaction and throw an error if it does
* If the database saving throws an error, check if it was before rolling back the fhir data and if it was, roll back the fhir data
* Check if an eCR already exists and bail out early with a nicer error message than a 500
* move the blob saving/deleting code to the client files
Fixes #69
=> fix: handle rollbacks on partially failed save

containers/ecr-viewer/src/app/data/metadataDb/utils/db-metadata.ts
_PR title: Remember to name your PR descriptively and follow [conventional commits](https://cheatsheets.zip/conventional-commits)!_
Fixes bug where migrations failed when metadata database is already set up, causing the application to be unusable.
N/A
Anything else the review team should know?
=> fix: migrations don't error out if database is previously set up

.github/workflows/createNewRelease.yaml
Commit both `docs` and `all-docs` folders to docs branch
=> ci: fix docs commit flow

containers/message-parser/requirements.txt
Pin `fhirpathpy` to fix test failures in message parser
=> fix: pin fhirpathpy in message parsing container

.github/workflows/trigger_demo_workflow.yaml
- Added a new GitHub Actions workflow file (trigger_demo_workflow.yaml) to enable manual deployment to the demo environment.
- The workflow accepts inputs for the service name and version, and triggers a secondary GitHub Actions workflow in `dibbs-tf-env`
- This initial PR is to test the permissions and integration with the `dibbs-tf-envs` repo. 
- I'll work directly with the team to customize the trigger as needed.
Once this merges to main:
- Manually trigger the workflow on GitHub.
- Verify that the API call is correctly made with the appropriate payload.
- Check the `dibbs-tf-envs` repo kicks off the appropriate job.
=> feat: add workflow to trigger deploy to demo environment

containers/ecr-viewer/e2e/dual/admin-program.spec.ts, containers/ecr-viewer/jest.setup.ts, containers/ecr-viewer/src/app/services/userService.ts
We're seeing a mystery bug where a user is somehow logged in, but their UUID/User is unavailable. @JNygaard-Skylight first saw this locally and we chalked it up to a strange dev state since logging out and logging back in fixed it, but we're now seeing it on the deployed version of the app. 
The leading culprit is the `cache` wrapping of the `getLoggedInUser` function. This is experimental in react@18, but is stable in react@19 - perhaps we try again later
=> fix: Remove `cache` wrapper on `getLoggedInUser` for now

containers/ecr-viewer/src/app/components/forms/FormPageContent.tsx, containers/ecr-viewer/src/app/tests/__snapshots__/ProgramAdminPage.test.tsx.snap, containers/ecr-viewer/src/app/tests/__snapshots__/UserAdminPage.test.tsx.snap
Change the div which saves space for the alerts to min height instead of height as the error alert is taller than the unsaved changes warning.
Fixes #841
=> fix: make space for error alert on forms

containers/ecr-viewer/e2e/dual/ecr-library.spec.ts, containers/ecr-viewer/e2e/dual/ecr-viewer.spec.ts
Change over usage of test ID as locator in e2e tests for role/label based lookups so we are a) closer to the user experience and b) more robust
=> test: remove usage of testid locators in e2e tests as much as possible

containers/ecr-viewer/src/app/services/listEcrDataService.ts
Our encounter date sorting has been sorting by create date for some time now, but our test data is so small that often turns out to be right 😬 
Fixes e2e test flakiness
=> fix: report_date => encounter_date

containers/ecr-viewer/package.json
- Set `Node` and `npm` versions in `package.json`
- Remove `version` since we aren't releasing `ecr-viewer` as a package
Fixes N/A
(I had an older version of Node (~`20`), and I was experiencing random-ish? test failures locally
=> build: Update Node and npm engine requirements

containers/ecr-viewer/seed-scripts/baseECR/star-wars/yoda-zika-v1-positive/CDA_RR.xml
Parts of the Reportability Information Organizer for the `yoda-zika-v1-positive` `RR` were in the wrong place -- moved it to the correct section.
- `External Resources` & the `Reporting Timeframe` info were moved under `Reportability Info Organizer`
N/A - saw this while working on another ticket
Template IDs:
- Reportability Information Organizer: `2.16.840.1.113883.10.20.15.2.3.13`
- ----> Reporting Timeframe: `2.16.840.1.113883.10.20.15.2.3.14`
- ----> External Resources: `2.16.840.1.113883.10.20.15.2.3.20`
Check the RR spec docs for correct template structure (Section `3.15` Reportability Information Organizer)
=> fix: update seed data with RR condition organizer section

containers/ecr-viewer/package-lock.json, containers/ecr-viewer/package.json, containers/ecr-viewer/src/app/utils/data-utils.tsx
Change array to element to not add a key if it's an object (this seems to already be happening by safe parse now). Also, update `html-react-parser` (not the issue, but might as well)
=> fix: safe parsing update and arrayToElement fix for modern times

containers/fhir-converter/Dockerfile
Updating the FHIR converter to include the XHTML fixes [here](https://github.com/CDCgov/dibbs-FHIR-Converter/pull/83).
=> chore: update converter with XHTML fix
